# Build Settings
markdown: kramdown

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

remote_theme: pages-themes/architect@v0.2.0    # sieht auch gut aus
#remote_theme: pages-themes/midnight@v0.2.0     # Favorit - schön schwarz
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/slate@v0.2.
#remote_theme: pages-themes/tactile@v0.2.0
