# Build Settings
markdown: kramdown

plugins:
# Themes
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Blog
#- jekyll-feed
#- jekyll-paginate
#- jekyll-seo-tag
#- jekyll-sitemap

#remote_theme: pages-themes/architect@v0.2.0    # Favorit hell
#remote_theme: pages-themes/midnight@v0.2.0     # Favorit dunkel
remote_theme: pages-themes/slate@v0.2.0        # hell
#remote_theme: pages-themes/tactile@v0.2.0      # hell

# Theme configuration
title: [title]
description: [desc]
